/**
 * @fileoverview POST /api/generate-zip route — create in-memory ZIP from GeneratedOutput
 * @module backend/routes/generateZip
 *
 * Security guarantees:
 *  - No files written to disk
 *  - No temporary directories created
 *  - No timestamps or dynamic metadata in the ZIP
 *  - Files sorted alphabetically before insertion (byte-level determinism)
 *  - All file entries use a fixed epoch date (deterministic metadata)
 */

import { Router } from 'express';
import JSZip from 'jszip';
import { GenerateZipRequestSchema } from '../../shared/schemas.js';
import { validateBody } from '../middleware/validateBody.js';

const router = Router();

// ---------------------------------------------------------------------------
// Fixed epoch date used for ALL ZIP file entries.
// This must never change — any drift would break byte-level determinism.
// ---------------------------------------------------------------------------
const ZIP_EPOCH = new Date('2000-01-01T00:00:00.000Z');

// ---------------------------------------------------------------------------
// Static supplemental files
// These are fully static: no timestamps, no generated-at comments, no env values.
// ---------------------------------------------------------------------------
const SUPPLEMENTAL_FILES = {
    'package.json': JSON.stringify(
        {
            name: 'reforge-output',
            version: '1.0.0',
            private: true,
            scripts: {
                dev: 'vite',
                build: 'vite build',
                preview: 'vite preview',
            },
            dependencies: {
                react: '^18.0.0',
                'react-dom': '^18.0.0',
            },
            devDependencies: {
                '@vitejs/plugin-react': '^4.0.0',
                vite: '^5.0.0',
            },
        },
        null,
        2
    ),
    'README.md': [
        '# ReForge Output',
        '',
        'This project was generated by ReForge.',
        '',
        '## Getting Started',
        '',
        '```bash',
        'npm install',
        'npm run dev',
        '```',
    ].join('\n'),
    '.gitignore': [
        'node_modules',
        'dist',
        '.env',
        '.env.local',
        '*.log',
    ].join('\n'),
};

// ---------------------------------------------------------------------------
// Shared ZIP builder — exported for reuse by generateFull route
// ---------------------------------------------------------------------------

/**
 * Assembles a GeneratedOutput into an in-memory ZIP buffer.
 *
 * Determinism invariants:
 *  - Files sorted alphabetically by path before insertion
 *  - All entries use ZIP_EPOCH (no system-time leakage)
 *  - DEFLATE level 9 (deterministic for identical inputs)
 *  - Supplemental files merged in only when not already present
 *
 * @param {import('../../shared/schemas.js').GeneratedOutput} generatedOutput
 * @returns {Promise<Buffer>} ZIP buffer
 */
export async function buildZipBuffer(generatedOutput) {
    const zip = new JSZip();
    const fileOptions = { date: ZIP_EPOCH, compression: 'DEFLATE', compressionOptions: { level: 9 } };

    // Collect all paths already supplied by the caller
    const suppliedPaths = new Set(generatedOutput.files.map((f) => f.path));

    // Merge supplemental files (only those not already present)
    const allFiles = [...generatedOutput.files];
    for (const [path, content] of Object.entries(SUPPLEMENTAL_FILES)) {
        if (!suppliedPaths.has(path)) {
            allFiles.push({ path, content, type: 'other' });
        }
    }

    // Sort alphabetically — deterministic insertion order
    allFiles.sort((a, b) => a.path.localeCompare(b.path));

    // Add all files under the project root prefix
    for (const file of allFiles) {
        zip.file(`project-root/${file.path}`, file.content, fileOptions);
    }

    return zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 9 } });
}

// ---------------------------------------------------------------------------
// Route
// ---------------------------------------------------------------------------

/**
 * POST /api/generate-zip
 *
 * Accepts a validated GeneratedOutput and returns a binary ZIP archive.
 *
 * Request body: { generatedOutput: GeneratedOutput }
 * Response: Binary ZIP stream (Content-Type: application/zip)
 *
 * IMPORTANT: No files are written to disk; no timestamps appear in the archive.
 */
router.post(
    '/generate-zip',
    validateBody(GenerateZipRequestSchema),
    async (req, res, next) => {
        try {
            const { generatedOutput } = req.body;

            const zipBuffer = await buildZipBuffer(generatedOutput);

            res.set('Content-Type', 'application/zip');
            res.set('Content-Disposition', 'attachment; filename="reforge-output.zip"');
            return res.send(zipBuffer);
        } catch (err) {
            return next(err);
        }
    }
);

export default router;
