/**
 * @fileoverview POST /api/generate-zip route — create in-memory ZIP from GeneratedOutput
 * @module backend/routes/generateZip
 *
 * Security guarantees:
 *  - No files written to disk
 *  - No temporary directories created
 *  - No timestamps or dynamic metadata in the ZIP
 *  - Files sorted alphabetically before insertion (byte-level determinism)
 *  - All file entries use a fixed epoch date (deterministic metadata)
 *  - All user-supplied paths are normalized then checked for traversal before use
 */

import path from 'node:path';
import { Router } from 'express';
import JSZip from 'jszip';
import { GenerateZipRequestSchema } from '../../shared/schemas.js';
import { validateBody } from '../middleware/validateBody.js';

const router = Router();

// ---------------------------------------------------------------------------
// Fixed epoch date used for ALL ZIP file entries.
// This must never change — any drift would break byte-level determinism.
// ---------------------------------------------------------------------------
const ZIP_EPOCH = new Date('2000-01-01T00:00:00.000Z');

// ---------------------------------------------------------------------------
// Static supplemental files
// These are fully static: no timestamps, no generated-at comments, no env values.
// ---------------------------------------------------------------------------
const SUPPLEMENTAL_FILES = {
    'package.json': JSON.stringify(
        {
            name: 'reforge-output',
            version: '1.0.0',
            private: true,
            type: 'module',
            scripts: {
                dev: 'vite',
                build: 'vite build',
            },
            dependencies: {
                react: '^18.0.0',
                'react-dom': '^18.0.0',
            },
            devDependencies: {
                '@vitejs/plugin-react': '^4.0.0',
                vite: '^5.0.0',
                tailwindcss: '^3.0.0',
            },
        },
        null,
        2
    ),
    'README.md': [
        '# ReForge Output',
        '',
        'This project was generated by [ReForge](https://github.com/reforge-app/reforge),',
        'an AI-powered frontend redesign tool.',
        '',
        '## Getting Started',
        '',
        '```bash',
        'npm install',
        'npm run dev',
        '```',
        '',
        '## Project Structure',
        '',
        'All generated source files are located under the `src/` directory.',
        'The entry point is `src/main.jsx`.',
    ].join('\n'),
    '.gitignore': [
        'node_modules',
        'dist',
        '.env',
        '.env.local',
        '*.log',
    ].join('\n'),
};

// ---------------------------------------------------------------------------
// Path safety guard
//
// Normalizes a caller-supplied file path using POSIX semantics, then rejects
// it if it still contains traversal sequences or is absolute.
//
// Attack examples blocked:
//   "foo/../../../etc/passwd"  → normalized → "../../etc/passwd" (contains ..)
//   "/etc/passwd"              → isAbsolute → true
//   "src/./App.jsx"            → normalized → "src/App.jsx"  (allowed)
//
// @param {string} filePath - Raw path from caller
// @returns {string|null} Normalized safe path, or null if path is unsafe
// ---------------------------------------------------------------------------
function normalizeSafePath(filePath) {
    const normalized = path.posix.normalize(filePath);

    if (
        !normalized ||
        normalized.trim() === '' ||
        normalized === '.' ||
        normalized.includes('..') ||
        path.posix.isAbsolute(normalized) ||
        normalized.startsWith('/')
    ) {
        return null;
    }

    return normalized;
}

// ---------------------------------------------------------------------------
// Shared ZIP builder — exported for reuse by generateFull route
// ---------------------------------------------------------------------------

/**
 * Assembles a GeneratedOutput into an in-memory ZIP buffer.
 *
 * Determinism invariants:
 *  - Files sorted alphabetically by path before insertion
 *  - All entries use ZIP_EPOCH (no system-time leakage)
 *  - DEFLATE level 9 (deterministic for identical inputs)
 *  - Supplemental files merged in only when not already present
 *
 * Security invariants:
 *  - Every user-supplied path is normalized then checked before use
 *  - Paths containing .. or absolute paths cause an immediate rejection
 *
 * @param {import('../../shared/schemas.js').GeneratedOutput} generatedOutput
 * @returns {Promise<{error: string}|Buffer>} ZIP buffer, or an object with error message
 */
export async function buildZipBuffer(generatedOutput) {
    // Per-file options: fixed epoch date + DEFLATE level 9
    const fileOptions = {
        date: ZIP_EPOCH,
        compression: 'DEFLATE',
        compressionOptions: { level: 9 },
    };

    // ── Path safety check on all caller-supplied files ──────────────────────
    for (const file of generatedOutput.files) {
        const safe = normalizeSafePath(file.path);
        if (safe === null) {
            const err = new Error(`Invalid file path: "${file.path}"`);
            err.statusCode = 400;
            err.code = 'INVALID_FILE_PATH';
            throw err;
        }
    }

    // ── Collect all paths already supplied by the caller ────────────────────
    const suppliedPaths = new Set(generatedOutput.files.map((f) => f.path));

    // ── Merge supplemental files (only those not already present) ────────────
    const allFiles = [...generatedOutput.files];
    for (const [filePath, content] of Object.entries(SUPPLEMENTAL_FILES)) {
        if (!suppliedPaths.has(filePath)) {
            allFiles.push({ path: filePath, content, type: 'other' });
        }
    }

    // ── Sort alphabetically for deterministic insertion order ────────────────
    allFiles.sort((a, b) => a.path.localeCompare(b.path));

    // ── Assemble ZIP ─────────────────────────────────────────────────────────
    const zip = new JSZip();

    for (const file of allFiles) {
        const safePath = normalizeSafePath(file.path) ?? file.path;
        zip.file(`reforge-output/${safePath}`, file.content, fileOptions);
    }

    return zip.generateAsync({
        type: 'nodebuffer',
        compression: 'DEFLATE',
        compressionOptions: { level: 9 },
    });
}

// ---------------------------------------------------------------------------
// Route
// ---------------------------------------------------------------------------

/**
 * POST /api/generate-zip
 *
 * Accepts a validated GeneratedOutput and returns a binary ZIP archive.
 *
 * Request body: { generatedOutput: GeneratedOutput }
 * Response: Binary ZIP stream (Content-Type: application/zip)
 *
 * IMPORTANT: No files are written to disk; no timestamps appear in the archive.
 */
router.post(
    '/generate-zip',
    validateBody(GenerateZipRequestSchema),
    async (req, res, next) => {
        try {
            const { generatedOutput } = req.body;

            const zipBuffer = await buildZipBuffer(generatedOutput);

            res.set('Content-Type', 'application/zip');
            res.set('Content-Disposition', 'attachment; filename="reforge-output.zip"');
            return res.send(zipBuffer);
        } catch (err) {
            return next(err);
        }
    }
);

export default router;
